
title: Ben Briesmeister's Blog
description: Stories and reflections from the life of a missionary


# This only applies to projects yielding code packages.
# Not applicable here since this is strictly a blog.
show_downloads: false

# specifies the URL format for generated blog URLs
permalink: /blog/:year/:categories/:slug


# When there's a Google Analytics account configured,
# we should update this to apply tracking.
# google_analytics: UA-XXXXX-X

author:
    name: Ben Briesmeister
    email: ben.briesmeister@gmail.com

# remote_theme: bbries/cayman@bbries
remote_theme: daviddarnes/alembic@master


# 3. Site navigation
navigation_header:
  Home: /
  # Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  # Fork Alembic: https://github.com/daviddarnes/alembic


navigation_footer:
  Ben's Blog: http://benb.blog/

# 4. Content generation settings
paginate: 5
paginage_path: /blog/posts/:num
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Los_Angeles # Timezone for blog posts and alike


# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: null
    feature_image: "https://picsum.photos/2560/600?image=866"



# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing


# Don't include these files/paths in Jekyll builds
exclude:
    - node_modules
    - Dockerfile
    - Gemfile
    - Makefile
    - scripts

# Modules that must be installed
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-default-layout
  - jemoji
