
title: Ben Briesmeister's Blog
description: Stories and reflections from the life of a missionary


# This only applies to projects yielding code packages.
# Not applicable here since this is strictly a blog.
show_downloads: false

# specifies the URL format for generated blog URLs
permalink: /blog/:year/:categories/:slug


# When there's a Google Analytics account configured,
# we should update this to apply tracking.
# google_analytics: UA-XXXXX-X

author:
    name: Ben Briesmeister
    email: ben.briesmeister@gmail.com
    
remote_theme: bbries/cayman@master

# NB. we have modified the cayman theme above.
# theme: jekyll-theme-cayman


exclude:
    - node_modules
    - Dockerfile
    - Gemfile
    - Makefile
    - scripts


plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-remote-theme
