
title: Ben Briesmeister's Blog
description: Meditations on the expansion of the Kingdom of God in real life


# This only applies to projects yielding code packages.
# Not applicable here since this is strictly a blog.
show_downloads: false

github:
    is_project_page: false

# specifies the URL format for generated blog URLs
permalink: /blog/:year/:categories/:slug


# When there's a Google Analytics account configured,
# we should update this to apply tracking.
# google_analytics: UA-XXXXX-X

theme: jekyll-theme-cayman



exclude:
    - node_modules
    - Dockerfile
    - Gemfile
    - Makefile
    - scripts
